import type {Change, ScopeOption} from './types.js'

export const changes: readonly Change[] = [
    {
        id: 'CR-104',
        title: 'Emergency lighting renewal',
        site: 'north-plant',
        statusFocus: 'active',
        risk: 'Critical',
        status: 'Ready for review',
        summary: 'Replace emergency luminaires before the winter maintenance window.',
        owner: 'J. Meyer',
        type: 'Safety',
        supplierInvolvement: true,
        safetyImpact: true,
        progress: 64,
        plannedStart: '2026-09-18',
        plannedCompletion: '2026-10-04',
        affectedAssets: ['Assembly hall', 'Emergency lighting circuit EL-2'],
    },
    {
        id: 'CR-118',
        title: 'Packaging-line guard upgrade',
        site: 'north-plant',
        statusFocus: 'planned',
        risk: 'High',
        status: 'Planned',
        summary: 'Install the approved interlocked guard during the next production stop.',
        owner: 'A. Sørensen',
        type: 'Machinery',
        supplierInvolvement: true,
        safetyImpact: true,
        progress: 18,
        plannedStart: '2026-10-12',
        plannedCompletion: '2026-10-16',
        affectedAssets: ['Packaging line 3', 'Guard controller GC-3'],
    },
    {
        id: 'CR-203',
        title: 'Warehouse racking inspection',
        site: 'warehouse',
        statusFocus: 'active',
        risk: 'Medium',
        status: 'In assessment',
        summary: 'Confirm remedial work after the annual racking inspection.',
        owner: 'R. Patel',
        type: 'Facilities',
        supplierInvolvement: false,
        safetyImpact: true,
        progress: 42,
        plannedStart: '2026-09-09',
        plannedCompletion: '2026-09-28',
        affectedAssets: ['Racking aisles A–F', 'Loading bay 2'],
    },
    {
        id: 'CR-221',
        title: 'Boiler-control procedure review',
        site: 'south-plant',
        statusFocus: 'completed',
        risk: 'Low',
        status: 'Completed',
        summary: 'Update the isolation procedure before the next contractor visit.',
        owner: 'M. Liu',
        type: 'Procedure',
        supplierInvolvement: false,
        safetyImpact: false,
        progress: 100,
        plannedStart: '2026-08-14',
        plannedCompletion: '2026-08-28',
        affectedAssets: ['Boiler house', 'Isolation procedure OP-17'],
    },
    {
        id: 'CR-237',
        title: 'Forklift charging relocation',
        site: 'warehouse',
        statusFocus: 'planned',
        risk: 'High',
        status: 'Awaiting approval',
        summary: 'Move charging bays away from outbound staging and renew ventilation.',
        owner: 'E. Novak',
        type: 'Facilities',
        supplierInvolvement: true,
        safetyImpact: true,
        progress: 8,
        plannedStart: '2026-11-02',
        plannedCompletion: '2026-11-20',
        affectedAssets: ['Charging bays 1–4', 'Outbound staging'],
    },
    {
        id: 'CR-244',
        title: 'Shift handover checklist',
        site: 'south-plant',
        statusFocus: 'active',
        risk: 'Medium',
        status: 'Pilot running',
        summary: 'Standardise maintenance handover across production and utilities.',
        owner: 'C. Jensen',
        type: 'Organisation',
        supplierInvolvement: false,
        safetyImpact: false,
        progress: 73,
        plannedStart: '2026-09-05',
        plannedCompletion: '2026-09-25',
        affectedAssets: ['Production shifts', 'Utilities team'],
    },
]

export const scopes: readonly ScopeOption[] = [
    {id: 'all', label: 'All sites'},
    {id: 'north-plant', label: 'North Plant'},
    {id: 'warehouse', label: 'Warehouse'},
    {id: 'south-plant', label: 'South Plant'},
]
